<a href="https://colab.research.google.com/github/gkdivya/ComputerVisionAI/blob/master/2DConvolutionUsingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np 
image = np.random.random((5,5)) 
image = np.around(image, decimals = 2)

In [13]:
image = np.pad(image, pad_width=1)

In [14]:
print("Image:", image)

Image: [[0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.05 0.5  0.83 0.59 0.18 0.  ]
 [0.   0.82 0.59 0.79 0.53 0.66 0.  ]
 [0.   0.16 0.36 0.43 0.93 0.68 0.  ]
 [0.   0.54 0.46 0.04 0.23 0.13 0.  ]
 [0.   0.4  0.61 0.22 0.12 0.52 0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]]


In [4]:
kernel = np.zeros((3,3), dtype=float) 

In [6]:
kernel[1][2] = 1

In [7]:
print(kernel)

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
output = np.zeros(5,5)

In [15]:
print(len(image))

7


In [ ]:
for i in range(len(image)):
  for j in range(len(image)):
    if j < kernel.size:
      
