<a href="https://colab.research.google.com/github/gkdivya/ComputerVisionAI/blob/master/2DConvolutionUsingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
image = np.random.random((5,5)) 
image = np.around(image, decimals = 2)

In [3]:
image = np.pad(image, pad_width=1)

In [4]:
print("Image:", image)

Image: [[0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.14 0.32 0.57 0.53 0.38 0.  ]
 [0.   0.21 0.62 0.72 0.2  0.19 0.  ]
 [0.   0.84 0.68 0.2  0.42 0.76 0.  ]
 [0.   0.38 0.03 1.   0.36 0.19 0.  ]
 [0.   0.6  0.89 0.67 0.63 0.62 0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]]


In [5]:
kernel = np.zeros((3,3), dtype=float) 

In [6]:
kernel[1][2] = 1

In [7]:
print(kernel)

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [11]:
output = np.zeros((5,5), dtype=float)
output

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
xImgShape, yImgShape = image.shape
xKernelShape, yKernelShape = kernel.shape


print(image.shape)
print(yImgShape - yKernelShape)

(7, 7)
4


In [30]:
print(image[0:3, 0:3])

[[0.   0.   0.  ]
 [0.   0.14 0.32]
 [0.   0.21 0.62]]


In [32]:
for y in range(yImgShape):
  print(y)
  if y >= yImgShape - yKernelShape:
    print("breaking for y")
    break

  for x in range(xImgShape):
    # Go to next row once kernel is out of bounds
    print(x)
    if x >= xImgShape - xKernelShape:
       break
    print("**************",image[x: x + xKernelShape, y: y + yKernelShape])
    #   print((kernel * image[x: x + xKernelShape, y: y + yKernelShape]).sum())
    #   output[x, y] = (kernel * image[x: x + xKernelShape, y: y + yKernelShape]).sum()      

print(output)

0
0
************** [[0.   0.   0.  ]
 [0.   0.14 0.32]
 [0.   0.21 0.62]]
1
************** [[0.   0.14 0.32]
 [0.   0.21 0.62]
 [0.   0.84 0.68]]
2
************** [[0.   0.21 0.62]
 [0.   0.84 0.68]
 [0.   0.38 0.03]]
3
************** [[0.   0.84 0.68]
 [0.   0.38 0.03]
 [0.   0.6  0.89]]
4
1
0
************** [[0.   0.   0.  ]
 [0.14 0.32 0.57]
 [0.21 0.62 0.72]]
1
************** [[0.14 0.32 0.57]
 [0.21 0.62 0.72]
 [0.84 0.68 0.2 ]]
2
************** [[0.21 0.62 0.72]
 [0.84 0.68 0.2 ]
 [0.38 0.03 1.  ]]
3
************** [[0.84 0.68 0.2 ]
 [0.38 0.03 1.  ]
 [0.6  0.89 0.67]]
4
2
0
************** [[0.   0.   0.  ]
 [0.32 0.57 0.53]
 [0.62 0.72 0.2 ]]
1
************** [[0.32 0.57 0.53]
 [0.62 0.72 0.2 ]
 [0.68 0.2  0.42]]
2
************** [[0.62 0.72 0.2 ]
 [0.68 0.2  0.42]
 [0.03 1.   0.36]]
3
************** [[0.68 0.2  0.42]
 [0.03 1.   0.36]
 [0.89 0.67 0.63]]
4
3
0
************** [[0.   0.   0.  ]
 [0.57 0.53 0.38]
 [0.72 0.2  0.19]]
1
************** [[0.57 0.53 0.38]
 [0.72 0.2  0.1