<a href="https://colab.research.google.com/github/gkdivya/ComputerVisionAI/blob/master/2DConvolutionUsingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
image = np.random.random((5,5)) 
image = np.around(image, decimals = 2)

In [3]:
image = np.pad(image, pad_width=1)

In [4]:
print("Image:", image)

Image: [[0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.77 0.03 0.58 0.03 0.19 0.  ]
 [0.   0.22 1.   0.3  0.21 0.68 0.  ]
 [0.   0.32 0.11 0.77 0.13 0.65 0.  ]
 [0.   0.63 0.84 0.86 0.94 0.05 0.  ]
 [0.   0.05 0.69 0.9  0.32 0.29 0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]]


In [5]:
kernel = np.zeros((3,3), dtype=float) 

In [6]:
kernel[1][2] = 1

In [7]:
print(kernel)

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [8]:
output = np.zeros((5,5), dtype=float)
output

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
xImgShape, yImgShape = image.shape
xKernelShape, yKernelShape = kernel.shape


print(image.shape)
print(yImgShape - yKernelShape)

(7, 7)
4


In [10]:
print(image[0:3, 0:3])

[[0.   0.   0.  ]
 [0.   0.77 0.03]
 [0.   0.22 1.  ]]


In [21]:
for x in range(xImgShape):
  # Go to next row once kernel is out of bounds
  if x > xImgShape - xKernelShape:
      break

  for y in range(yImgShape):
    # Go to next column once kernel is out of bounds
    if y > yImgShape - yKernelShape:
      break

    output[x, y] = np.sum(kernel * image[x: x + xKernelShape, y: y + yKernelShape])  

print(output)

[[0.03 0.58 0.03 0.19 0.  ]
 [1.   0.3  0.21 0.68 0.  ]
 [0.11 0.77 0.13 0.65 0.  ]
 [0.84 0.86 0.94 0.05 0.  ]
 [0.69 0.9  0.32 0.29 0.  ]]
